### ISSUE TITLE
dolazak/odlazak

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim6#14]
Nigdje nemate funkcionalnost da li je neka rezervacija iskorištena. Tj. evidencija da je klijent došao, a zatim otišao. Ako postoji rezervacija to ne znači da je sto stvarno bio zauzet. Ovo bi trebalo biti jasno vidljivo na pregledu stolova. Npr. sto koji je rezervisan u tom terminu a prazan je, označen jednom bojom, a sto za kojim ljudi sjede je označen drugom.

**Comment by tarikdemirovic** [comment]
azuriran FZ 3.2.3.3. (modifikacija rezervacije)
