### ISSUE TITLE
Validacija - dodavanje korisnika

### ISSUE THREAD

**Issue by dzbricic** [SoftverInzenjeringETFSA/SI2014Tim6#19]
Komponenta: Dodavanje korisnika

commit ID: 3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema: Ne zna se kakav je to ispravan format za šifru
http://pokit.org/get/?67ed993e483e744586e3990711bbc0ab.jpg

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa login podacima "sefic" i šifrom "123Sifra"
2. Otvoriti Radnici tab
3. Odabrati radnika, zatim kliknuti na "Dodaj korisnika"
4. Unijeti neke podatke

**Comment by aidagranulo** [comment]
Dodana labela koja pri samom otvaranju forme opisuje kakav je format unosa te samim tim smanjuje mogućnost pogreške korisnika i jasnije objašnjava format unosa.

commit ID: 213a230176af6134b7e44333efb001c911ba51c7
