### ISSUE TITLE
Tabela za prikaz radnika

### ISSUE THREAD

**Issue by dzbricic** [SoftverInzenjeringETFSA/SI2014Tim6#20]
Komponenta: Prikaz radnika

commit ID: 3006ae0

Opis problema: Ne vidi se fino datum zapošljavanja
http://pokit.org/get/?2c9408518e5f1965a191b811b80abd43.jpg

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa login podacima "sefic" i šifrom "123Sifra"
2. Otvoriti tab Radnici

**Comment by AnesaDrakovac** [comment]
Prema projektnom zadatku 10 piše da neće biti priznavani bugovi koji su očigledna posljedica odabrane tehnologije i dizajna.

Stoga, smatram da ovaj bug nije validan jer, da bi se pogledao datum, u tabeli se lahko može pomjeriti linija za povećanje širine kolone. (http://prntscr.com/7aw8jg)
