### ISSUE TITLE
Opcije za generisanje izvještaja

### ISSUE THREAD

**Issue by dzbricic** [SoftverInzenjeringETFSA/SI2014Tim6#21]
Komponenta: Opcije za generisanje izvještaja

commit ID: 3006ae0

Opis problema: Ne vidi se fino jedna od ponuđenih opcija
http://pokit.org/get/?7542b2982e738f816ca6d4ae236d54d4.jpg

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa login podacima "sefic" i šifrom "123Sifra"
2. Otvoriti tab Izvještaji

**Comment by aidagranulo** [comment]
Smanjen font na opcijama za generisanje izvještaja.
commit ID: 213a230176af6134b7e44333efb001c911ba51c7
