### ISSUE TITLE
Pretraga radnika

### ISSUE THREAD

**Issue by dzbricic** [SoftverInzenjeringETFSA/SI2014Tim6#22]
Komponenta: Pretraga radnika

commit ID: 3006ae0

Opis problema: Nakon pretrage određenog radnika, te brisanja istog, nije moguće vidjeti ostale radnike. 

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju sa login podacima "sefic" i šifrom "123Sifra"
2. Otvoriti tab Radnici

**Comment by AnesaDrakovac** [comment]
Komponenta je 'Radnici' ili 'Radnici.java'. ID Commita takođe nije tačan. ID posljednjeg commita ove komponente je: 4121f6a.

Bug je ipak ispravljen, ali za ubuduće pogledajte primjer dobro prijavljenog buga u Projektnom zadatku 10.
Commit ID ispravke: 4824bb0
