### ISSUE TITLE
Nepostojeci radnik

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#23]
Komponenta: Radnici

commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema:
Nakon brisanja radnika, za koji je napravljen korisnički račun, ostane korisnički račun sa nepostojecim id-om radnika.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju i prijaviti se kao šef
2. Dodati radnika ako već ne postoji
3. Napraviti korisnički račun za radnika
4. Izbrisati gore navedenog radnika

**Comment by ElmirHodzic** [comment]
Resolved
