### ISSUE TITLE
Generisanje izvjestaja

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#24]
Komponenta: Izvjestaji

Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema:
Ne radi generisanje izvještaja ni jednog tipa izvještaja. Ne generiše se izvještaj i ne prikaže nikakvu obavijest.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju i prijaviti se kao šef
2. Kliknuti na dugme Izvještaji
3. Odabrati datume i kliknuti na generisanje izvještaja

**Comment by ElmirHodzic** [comment]
Pokušaj sada.
