### ISSUE TITLE
Poruka kod izvještaja

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#25]
Komponenta: Izvjestaji

Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema:

Kod generisanja izvještaja se ne vidi cijela poruka o pogrešnom unosu.

Koraci za reproduciranje problema:
1. Otvoriti aplikaciju i prijaviti se kao šef
2. Odabrati dugme Izvještaji
3. Kliknuti na dugme Generiši

**Comment by AnesaDrakovac** [comment]
Ispravljeno.

Commit ID: 0f54619
