### ISSUE TITLE
Oznacavanje rezervacija

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#27]
Komponenta: RezervacijaRadnik

Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema:
Zauzeti stolovi trebaju biti crveni umjesto narandzasti i rezervisani trebaju biti narandzasti umjesto crveni.

Koraci za reproduciranje problema:
1. Otvoriti aplikaciju i prijaviti se kao radnik
2. Rezervisati sto
3. Otvoriti rezervaciju i kliknuti na okupiran sto

**Comment by AlminHalilovic** [comment]
Ispravljeno.
