### ISSUE TITLE
Jedinica vremena kod rezervacije

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#28]
Komponenta: NapraviRezervaciju

Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/3006ae0b8511d258199f3791d4a2f066bf044c96

Opis problema: 

Nije prikazana jedinnica vremena trajanja kod pravljenja rezervacije

Koraci za reproduciranje problema:
1. Otvoriti aplikaciju i prijaviti se kao radnik
2. Kliknuti na neki slobodni sto

**Comment by AnesaDrakovac** [comment]
Niste naveli validan commit ID, ali je ispravljeno.

Commit ID: 636f2da
