### ISSUE TITLE
Login podaci za pristup bazi ne odgovaraju traženim postavkama

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#29]
**Komponenta:**
_hibernate.cfg.txt_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Iako je u postavci projetka navedeno da se za pristup bazi koristi kao username "EtfSI2014" i password "2014SIEtf", to ovdje nije korišteno i aplikacije nema pristupa bazi podataka.

**Koraci za reproduciranje problema:**
Pokušaj da se pokrene aplikacija je bio neuspješan

**Dobijeni rezultat:**
Greška koja indicira da korisnik _root@localhost_ nema privilegije nad nad bazom _tim6_

**Očekivani rezultat:**
Pokretanje aplikacije

**Comment by tarikdemirovic** [comment]
Popravljeno.
ID:
0f5461978d1dcb28e300ede48973e74501af06f6
