### ISSUE TITLE
Ime baze ne odgovara imenu iz uputstva

### ISSUE THREAD

**Issue by ElmaKusundzija** [SoftverInzenjeringETFSA/SI2014Tim6#30]
Komponenta:
'hibernate.cfg.xml'

commit ID:
41efc711456e06678217e9cc6e0f4e58cdf88f5b

Opis problema:
Navedeno je da je ime baze 'tim6', ali je koristeno ime 'restoran'.

Koraci za reproduciranje problema:
1. Pokrenuti  "App.java" .

Dobijeni rezultat:
Greška nemogućnosti pristupa bazi 'restoran'.

Očekivani rezultat:
Pokretanje aplikacije.

**Comment by tarikdemirovic** [comment]
Popravljeno.

ID:
0f5461978d1dcb28e300ede48973e74501af06f6
