### ISSUE TITLE
Nemoguće se prijaviti na aplikaciju

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#31]
**Komponenta:**
_LoginScreen.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Nemoguće se prijaviti na aplikaciju, javlja grešku da password nije u ispravnom formatu, te je nemoguće koristiti aplikaciju.

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. pokušati se prijaviti sa ispravnim podacima (sefica, 123sifra)

**Dobijeni rezultat:**
Poruka koja javlja da nije ispravan format za šifru
Ima li [link slike](http://pokit.org/get/img/06980a67ba09ce9566d7616d0dd2f387.png) koji demonstrira prijavljenu grešku.

**Očekivani rezultat:**
Startanje glavnog prozora ili, eventualno, prijava o netačnim podacima.

**Comment by tarikdemirovic** [comment]
Je li sefica il sefic?

**Comment by tarikdemirovic** [comment]
Popravljeno.

**Comment by EnilPajic** [comment]
Bilo je 'sefic', ali svejedno, ako ništa, pogrešna poruka, trebalo je možda "netačni podaci" :)

**Comment by tarikdemirovic** [comment]
Bit' će popravljeno haha

**Comment by AnesaDrakovac** [comment]
Nije dobar navedeni commit ID, ali je ispravljeno u sklopu sljedećeg commita.

Commit ID: 29cff79
