### ISSUE TITLE
Validacija imena i prezimena

### ISSUE THREAD

**Issue by ElmaKusundzija** [SoftverInzenjeringETFSA/SI2014Tim6#32]
Komponenta:
'RadniciDodavanje.java'

commit ID:
41efc71

Opis problema:
Nemoguće unijeti velika slova Č,Ć,Dž,Đ,Š (ime i prezime)

Koraci za reproduciranje problema:
1. Pokrenuti "App.java" .
2. Unijeti username 'sefic' , password  '123Sifra'
3. Odaberemo opciju 'Dodaj Radnika'
4. Unesemo podatke gajd je prezime npr. 'Šabanović'

Dobijeni rezultat:
Nedozvoljen format prezimena

Očekivani rezultat:
Dodavanje radnika

**Comment by aidagranulo** [comment]
Ispravljeni regexi za validaciju podataka, dodana velika slova č.š,đ,ž.
commit ID: b7b76f3e932f023ee826ba5505e7ef3a3f74a208
