### ISSUE TITLE
Invalidna provjera JMBG-a

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#33]
**Komponenta:**
_RadniciDodavanje.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Validacija JMBG-a nije ispravna. Mogu uniijeti npr. _1234567891230_ što naravno nije ispravan matični broj. Funkcija za provjeru koristi _RegEx_ **[0-9]{13}** što znači da _samo_ traži unos 13 brojeva, ali ne specificira kojih brojeva.
#### Prijedlog: koristiti validaciju kao na [ovom linku](http://jmbg.brmbrm.com/#check-more).

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. Prijaviti se kao šef
    3. klikom na dugme _Dodaj radnika_ otvara se nova forma
    4. unesu se potrebni podaci, i kao JMBG se unese netačan, npr. _1231231231231_

**Dobijeni rezultat:**
Dodan radnik, iako je netačan JMBG

**Očekivani rezultat:**
Prijava greške o pogrešnom JMBG

**Comment by AnesaDrakovac** [comment]
Ispravljeno.

Commit ID: d23851c
