### ISSUE TITLE
Neuobicajen format sifre pri dodavanju korisnika

### ISSUE THREAD

**Issue by spahicharis** [SoftverInzenjeringETFSA/SI2014Tim6#34]
Komponenta:
DodavanjeKorisnika.java

commit ID:
78955ac5076eec33a7957d4b305da7a5ef816fcd

Opis problema:
Na formi "Dodavanje korisnika" pri unosu sifre ne prolaze one koje su u obliku "Abcdef11", "abcdeF11". 

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Selektovati korisnika/radnika iz tabele.
3. Kliknuti na dugme "Dodaj korisnika".
4. Nakon otvaranja nove forme, unijeti potrebne podatke u polja "Korisnicko ime" i "Sifra".
5. U polje "Sifra" unijeti vrijednost "Abcdef11".
6. Kliknuti na dugme "Dodaj korisnika".

Dobijeni rezultat:
- Na trenutnoj formi kod polja "Sifra:" javlja gresku "Nedozvoljen format!" iako postoje uputstva
  koja kazu da se sifra sastoji od 1 broja, 1 velikog slova i 1 malog slova pri cemu duzina mora biti veca od 5.

Očekivani rezultat:
- Ocekuje se da ovaj format sifre bude validan s obzirom da nigdje nije precizno naveden.

**Comment by aidagranulo** [comment]
Ispravljen regex i pravilno pozivanje metode u formama LoginScreen i DodavanjeKorisnika.
commit ID: 29cff797ae91197e04058f3c9bcc3669964b1fda
