### ISSUE TITLE
Nema opcije za dodavanje VIP klijenta

### ISSUE THREAD

**Issue by spahicharis** [SoftverInzenjeringETFSA/SI2014Tim6#35]
Komponenta:
DodavanjeKlijentaSef.java

commit ID:
2e43cc92bb6b1f883f64fb7ed1fbdd19fd57db4f

Opis problema:
Na formi "Dodavanje klijenta" na koju se ulogiram kao "Sef" ne postoji dodavanje klijenta kao VIP.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Kliknuti na dugme Klijenti sa lijeve strane.
3. Kliknuti na dugme "Dodaj novog klijenta".
4. Otvara se nova forma.

Dobijeni rezultat:
Na otvorenoj formi ne postoji opcija koja klijenta oznacava kao VIP.

Očekivani rezultat:
Prema dokumentu (https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/blob/master/UISSI_ver1.pdf) trebalo bi da postoji opcija za to.

**Comment by tarikdemirovic** [comment]
Napravljeno je da se klijent naknadno edituje u VIP. Ali kao što kažeš nije u skladu sa dokumentacijom.
