### ISSUE TITLE
Generisanje izvjestaja statistika

### ISSUE THREAD

**Issue by mirhat** [SoftverInzenjeringETFSA/SI2014Tim6#36]
Komponenta: Izvjestaji

Commit ID: https://github.com/SoftverInzenjeringETFSA/SI2014Tim6/commit/21d3936ea4495470a9b5ac0f5b6c6a7f82a3fd05

Opis problema:
Na izvjestaju pise da je broj uspješnih i neuspjesnih rezervacija 0 iako ima rezervacija u bazi

Koraci za reproduciranje problema:
1. Otvoriti aplikaciju i prijaviti se kao radnik
2. Dodati nekoliko rezervacija
3. Prijaviti se kao sef i odabrati dugme za Izvjestaje
4. Odabrati datume i generisati izvjestaj za statistiku

Dobijeni rezultat:
http://pokit.org/get/?c08ce07f87dc13f2378b8de5387b627e.jpg

Ocekivani rezultat:
Dvije rezervacije kao sto su u bazi http://pokit.org/get/?94c94d9c9879f80d536445eb673face9.jpg

**Comment by ElmirHodzic** [comment]
ocekivani rezultat ti ne valja, statistike se prave za uspjesno zavrsene rezeravacije odnosno rezervacije koje nisu uspjesne. Uradi sljedeci niz koraka okoncaj neku od rezervacija uspjesno odnosno možeš i sačekati da se neke rezervacije završe bez ručnog okončavanja onda izgeneriši taj izvještaj.

**Comment by mirhat** [comment]
u vas je uspjesna rezervacija samo ako se okupira i oslobodi :D a sta ako se samo okupira logicno da se nekad mora i osloboditi

**Comment by ElmirHodzic** [comment]
uspjesna je i kada see okupira i prođe određeni period nakon okupacije tacnije 3 sata.
