### ISSUE TITLE
Nepostojanje unit testova (forme)

### ISSUE THREAD

**Issue by ElmaKusundzija** [SoftverInzenjeringETFSA/SI2014Tim6#39]
Komponenta:
sve forme koje sadrze bilo kakvu validaciju unutar ba.unsa.etf.si.app.rezervacijaZGTim6.Forme

commit ID:
41efc71

Opis problema:
Ne postoje unit testovi za validaciju unosa, na bilo kojoj od gore navedenih formi

**Comment by tarikdemirovic** [comment]
Commit ID:
41e33dfa2a6ea9d4f9773251d77fbb11b5b161df
