### ISSUE TITLE
Nemoguće unijeti (validno) ime/prezime klijenta

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#40]
**Komponenta:**
_KlijentDodavanje.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Nemoguće je dodati novog klijenta sa validnim bosanskohercegovačkim imenima ili prezizimenima.

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. Logirati se kao šef
    3. Kliknuti na dugme _Klijenti_
    4. Kliknuti na dugme _Dodaj novog klijenta_
    5. Unijeti neke podatke, npr. ime "Ćamil" ili prezime "Đulep"

**Dobijeni rezultat:**
Poruka koja javlja da nije ispravan format imena/prezimena

**Očekivani rezultat:**
Dodavanje klijenta sa unesenim podacima
#### Note
- _Ovaj commit je napravljen pred kraj 'dozvoljenog' vremena za slanje projekata (takav commit je validan za testiranje, a bug-ovi u njemu su validni), te je navedena greška vjerovatno uklonjena u novijim verzijama._
- _Sličan bug je već prijavljen, ali on se nalazi na **drugoj** formi, tj. u drugom modulu/dijelu aplikacije, te je i ovaj validan._

**Comment by AlminHalilovic** [comment]
Ovo je kolegica Elma već napisala.

**Comment by EnilPajic** [comment]
Bug se nalazi na drugoj formi, u skroz drugom dijelu aplikacije (od Elme može biti kada radnik unosi klijenta a ovo kada šef), i ne znači da se ispravljanjem bug-a na jednoj formi ispravlja i drugi bug.
Nigdje ne piše da se bugovi sa različitih formi tretiraju isto :D (vi odličite šta hoćete ;))
Sasvim je bilo moguće da se validacije radili **odvojeno** na obje forme, pa ako ispravite prvu bug na jednoj formi, on bi ostao na drugoj.

**Comment by AlminHalilovic** [comment]
Aha, nisam primjetio da je druga forma, ali u svakom slučaju zaboravljena je obrada unosa naših slova. Prilikom ispravljanja ćemo pokriti sve forme i unos u bazu. :)

**Comment by aidagranulo** [comment]
Ispravljen regex za validaciju.
commit ID: b7b76f3e932f023ee826ba5505e7ef3a3f74a208
