### ISSUE TITLE
Moguće je kreirati rezervaciju za vrijeme u prošlosti

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#41]
**Komponenta:**
_RezervacijaRadnik.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Moguće je napravitirezervacije u prošlom vremenu (npr. neko da rezerviše stol u 14:00 a sada je 19:00). Ipak, za datum, ovo je onemogućeno, što je ispravno ponašanje :)

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. Logirati se kao radnik (user `radnik`, pass: `123Sifra`)
    3. Promijeniti vrijeme rezervacije na neko prethodno (npr. ako je sada `19:00` mi promijenimo na `13:00`)
    4. Kliknuti na dugme `Osvjezi`
    5. Kliknuti na neki od slobodnih stolova i izvršiti rezervaciju

**Dobijeni rezultat:**
Upješno rezerviranje stola

**Očekivani rezultat:**
Prijava greške da se stol ne može rezervirati u prošlosti
#### Note
- _Ovaj commit je napravljen pred kraj 'dozvoljenog' vremena za slanje projekata (takav commit je validan za testiranje, a bug-ovi u njemu su validni), te je navedena greška vjerovatno uklonjena u novijim verzijama._

**Comment by AlminHalilovic** [comment]
Ovo nije greška i u skladu je i sa SRS-om i sa dogovorom sa asistentom. Omogućeno je da se može kreirati rezervacija u toku aktivnog dana u "prošlom vremenu" kako bi radnik mogao u slučaju zaborava neke rezervacije ili okupacije istu uspješno obaviti.

**Comment by EnilPajic** [comment]
Nažalost ni ovo nisam našao u SRS-u (niti `SRSSI_ver1.pdf` niti `SRSSI_ver2.pdf`), a tražio sam u poglavlju `3.2.3`. Ja se izvinjavam ako sam to previdio, pa mi neko može referencirati taj dio koji kaže da se rezervacija može kreirati za vrijeme koje je proteko.
Ne znam kako tumačiti te stvari "dogovor sa asistentom", pa se neću miješati :) Neka asistent odluči (ako ja nisam pogriješio pa nisam vidio da nema u SRS-u) :)

**Comment by AlminHalilovic** [comment]
Greška kao takva može, a i ne mora proći. U SRS-u nigdje ne stoji da se rezervacija ne može kreirati u prošlom vremenu za neki dan, tako da je to lični dojam o prisustvu greške u tome. U ovom slučaju postoji razlog zbog kojeg je ostavljena mogućnost takvog kreiranja rezervacije te se po potrebi isti može i modifikovati da se to zabrani.
