### ISSUE TITLE
Nemoguće "iskoristiti" vrijeme kada stolovi nisu rezervirani

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#42]
**Komponenta:**
_RezervacijaRadnik.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Ovdje je malo teže opisati, ide ovako: Ako je sada `19:10` i ja sam se logirao kao radnik, i klijent _Enil Pajić_ hoće da rezerviše stol `22` u `22:10`, ja (radnik) promijenim vrijeme na `22:10`, kliknem `Osvjezi` i odaberem stol `22` da bih rezervirao 2 sata Enilu.
Problem nastaje onda što vrijeme od `19:10` do `22:10` nije moguće iskostiti za neku novu rezervaciju, jer ako se vratim sa vremenom na `19:10`, kliknem `Osvjezi`, pa na stol `22`, ono piše `Do isteka rezervacije 4 sati` te ja (radnik) ne mogu ponovo da rezervišem taj stol (za npr 1h od `19:20` do `20:20`).

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. Logirati se kao radnik (user `radnik`, pass: `123Sifra`) (u npr. `19h`)
    3. Kao što je opisano u _Opisu problema_, promijenim vrijeme 2h unaprijed 
    4. Kliknuti na dugme `Osvjezi`
    5. Kliknuti na neki od slobodnih stolova i izvršiti rezervaciju na 2h
    6. Kliknuti na dugme `Osvezi`
    7. Vratiti vrijeme na trenutno aktualno (npr. `19h')
    8. Kliknuti na dugme`Osvjezi`
    9. Pokušati rezervirati isti stol (jer bi u tom terminu trebao biti slobodan)

**Dobijeni rezultat:**
Stol je zauzet tj. prozor koji nudi opcije otkazivanje rezervacije i koji ispisuje poruku da je stol zauzet sljedeća 4h

**Očekivani rezultat:**
Mogćunost rezervacije stola u slobodnom terminu
#### Note
- _Ovaj commit je napravljen pred kraj 'dozvoljenog' vremena za slanje projekata (takav commit je validan za testiranje, a bug-ovi u njemu su validni), te je navedena greška vjerovatno uklonjena u novijim verzijama._

**Comment by AlminHalilovic** [comment]
Ovo nije greška i postavljeno je namjerno da se ne može neki stol rezervisati ukoliko ne ispunjava vremensku kvotu od recimo 2 ili 3 sata( ne sjećam se koliko je tačno dogovoreno) za rezervaciju/okupaciju nekog stola.

**Comment by EnilPajic** [comment]
Navedno je tačno :) ali ga, nažalost, nisam uspio naći u SRS-u (`SRSSI_ver1.pdf` fajl, `3.2.3` poglavlje, tačnije potpoglavlje `3.2.3.1 Rezervacija stola`) pa je onda greška u SRS-u koja je, u tome slučaju, validna. Tj. ovo se markira kao "neusklađenost aplikacije sa SRS-om" :)

**Comment by AlminHalilovic** [comment]
Kao takva, greška onda može proći. :)
