### ISSUE TITLE
Ne koristi se Unicode encoding prilikom čitanja iz baze

### ISSUE THREAD

**Issue by EnilPajic** [SoftverInzenjeringETFSA/SI2014Tim6#43]
**Komponenta:**
_IzmjenaKlijentaSef.java_

**CommitID:**
41efc711456e06678217e9cc6e0f4e58cdf88f5b

**Opis problema:**
Učitavanje netačnih podataka prilikom izmjene klijenta (ne učita dobro "naša" slova, č, ć, š. đ, ž)

**Koraci za reproduciranje problema:**
    1. pokrenuti aplikaciju
    2. Logirati se kao šef (user `sefic`, pass: `123Sifra`)
    3. Kliknuti na `Klijenti`
    4. Odabrati nekog klijenta
    5. Kliknuti na dugme `Izmijeni klijenta`

**Dobijeni rezultat:**
Pogrešni podaci, iz baze se ne učitaju podaci ispravno, tj. prilikom _query_-a ka bazi podataka nije vođeno računa o odgovarajućem _encoding_-u.
Sljedeća [slika](http://pokit.org/get/img/bb5b011ff78970786ae72aafae30d25f.png) to demonstrira.
Pošto je dozvoljeno unijeti slovo `ć`, tj. _RegEx_ za validaciju to dozvoljava, očekuje se da se isto i učita...

**Očekivani rezultat:**
Ispravno učitano prezime, `Pajić`.
##### Prijedlog: Nisam siguran kako ste rješavali problem _encoding_-a, ali za `Unicode` rad sa `MySQL` bazom je dovoljno naštimati da je `collation` od baze `UT8` i da se prije bilo kojeg _query_-a izvrši sljedeća komanda

``` sql
SET NAMES UTF8
```
#### Note
- _Ovaj commit je napravljen pred kraj 'dozvoljenog' vremena za slanje projekata (takav commit je validan za testiranje, a bug-ovi u njemu su validni), te je navedena greška vjerovatno uklonjena u novijim verzijama._

**Comment by AlminHalilovic** [comment]
Već si napisao sličnu grešku za pogrešan unos naših slova kroz aplikaciju. Mislim da ovo spada u taj tip greške. Kolegica je već to napisala prije tebe.

**Comment by EnilPajic** [comment]
Kolega, to nije isti tip greške. Ni blizu. Prvi se odnosi na validaciju (a što je Elma napisala ne odnosi se na toj formi, pročitaj komentar o Issue-u "Izmjena klijenta"), a ovo drugo se odnosi na rad sa bazom. 

Onaj `RegEx` koji validira ime/prezime ima `\uxxxx` a to **_nema ama baš nikakve veze_** sa učitavanjem iz baze i prikazivanjem pogrešnih znakova.

**Comment by AlminHalilovic** [comment]
Slažem se kolega. Nije bilo namjere da te oštetim. Prijavljene su 3 greške oko unosa i obrade naših slova( baza i forme u aplikaciji). Riješit će se prilikom ispravljanja obrade slova i greške u bazi i greške u aplikaciji. :)

**Comment by EnilPajic** [comment]
Okay, okay, samo naprijed! :)

Recimo da ja kao tester ne znam da će ispravljanje jedne greške ispraviti i drugu, po tom principu sam išao :)

**Comment by ElmirHodzic** [comment]
Resolved
Commit ID:
41e33dfa2a6ea9d4f9773251d77fbb11b5b161df
