### ISSUE TITLE
Moguce rezervisati sto, iako je vec u to vrijeme rezervisan

### ISSUE THREAD

**Issue by ElmaKusundzija** [SoftverInzenjeringETFSA/SI2014Tim6#44]
Komponenta:
'NapraviRezervaciju.java'

commit ID:
41efc71

Opis problema:
Moguce je rezervisati sto npr u 12:00 h popodne, u trajanju od 5 sati, iako je vec rezervisan taj isti dan od 15:00 h.

Koraci za reproduciranje problema:
1. Pokrenuti "App.java" .
2. Unijeti username 'radnik' , password '123Sifra'
3.Odaberemo datum 24.Aug i vrijeme 15:00 h
4. Rezervisemo za klijenta u trajanju 2 sata
5. vratimo se na panel
6. Odaberemo datum 24.Aug i vrijeme 12:00 h
7. rezervisemo za klijenta u trajanju 5 sati

Dobijeni rezultat:
Rezervacija vec rezervisanog vremena

Očekivani rezultat:
Mogucnost rezervacije samo 3 sata

**Comment by AlminHalilovic** [comment]
Ispravljeno
Commit ID: 7a082462a3
