### ISSUE TITLE
Nepostojeci test za klasu "ZauzetiSto"

### ISSUE THREAD

**Issue by edos11** [SoftverInzenjeringETFSA/SI2014Tim6#45]
Komponenta:
Obrazac "ZauzetiSto"

commit ID:
ea82d45

Opis greške:
Ne postoji junit test za klasu ZauzetiSto.java

**Comment by AlminHalilovic** [comment]
Komponenta se zove OkupiranSto, ovo je duplicirani issue jer je kolegica Elma to već obradila u issue #39.
