### ISSUE TITLE
Unos Radnika

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#50]
Na polju unos radnika nije validirano polje naziv posla tako da se moze unijeti bilo sta sto nije smisleno.

![slika bug](https://cloud.githubusercontent.com/assets/11410413/7893840/47b9706c-0662-11e5-9046-71a5d7e35232.jpg)

**Comment by aidagranulo** [comment]
Ispravljena validacija na navedenom polju.
commit ID: 83165e061daec92c6fbff1073a31c6783b3d4315
