### ISSUE TITLE
Pretraga radnika

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#51]
U tabu za pretragu radnika pretraga radi na cudan nacin. Mislim da bi ovo trebali ispraviti da vrsi pretragu abecedno po imenu a ne da trazi ima li negdje slovo uneseneo za imena. Drugi problem je da ako se unesu brojevi a ocekuje se ime ne bi trebali vrsiti pretragu jer ona nema smisla jer nije pretraivanje po datumu.
![ime bug 1](https://cloud.githubusercontent.com/assets/11410413/7894499/a474f666-066a-11e5-8d5b-bb35389ffb7a.jpg)
![ime bug 2](https://cloud.githubusercontent.com/assets/11410413/7894502/a9240a62-066a-11e5-82e7-ad900f68cb7c.jpg)

**Comment by AlminHalilovic** [comment]
Kolega, u SRS-u nigdje nije specificiran način pretrage, a i pretraga radi dobro, odnosno ne pojavljuju se greške tokom pretraživanja radnika, tako da ovo neće biti ispravljeno. Također, nigdje nije naveden ID commita te prijava greške se ne slaže s onom koja je specificirana u projektnom zadatku 10.
