### ISSUE TITLE
Dodavanje Radnika

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#52]
Prolazi pogresan format JMBGa jer moze proci i za sljedeci unos.

![jmbg](https://cloud.githubusercontent.com/assets/11410413/7894608/342bdda4-066d-11e5-947d-74a136de4342.jpg)

**Comment by AnesaDrakovac** [comment]
#33 

Obratite pažnju na već prijavljenje bugove i na primjer dobro prijavljenog buga.

Niste naveli:

Komponentu,
Commit ID,
Korake za reproduciranje problema,
Dobijeni rezultat,
Očekivani rezultat.
