### ISSUE TITLE
Ucitavanje radnika

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#53]
Nije dobro ucitavanje ne radi za Č,Ć...
![ucitavanje](https://cloud.githubusercontent.com/assets/11410413/7894653/1e96be36-066e-11e5-8dad-965e88193376.jpg)

**Comment by AnesaDrakovac** [comment]
#43

Obratite pažnju na već prijavljenje bugove i na primjer dobro prijavljenog buga.

Niste naveli:
- Komponentu,
- Commit ID,
- Korake za reproduciranje problema,
- Dobijeni rezultat,
- Očekivani rezultat.
