### ISSUE TITLE
Problem logina na radnika

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#54]
Ne moze se logirati na radnika sa datim passwordom. Kaze da je nedozvoljen format iako je identican passwordu za login admina tj "123Sifra". 

![radnik](https://cloud.githubusercontent.com/assets/11410413/7894745/48b78590-0670-11e5-9e46-35c76657e127.jpg)

**Comment by aidagranulo** [comment]
Kolega, 
ukoliko nije problem, možeš li navesti commit ID, jer i ako je ovakva greška postojala trebala bi biti ispravljena?

**Comment by tarikdemirovic** [comment]
Format prijave issuea: http://c2.etf.unsa.ba/mod/resource/view.php?id=41041

**Comment by Strojki** [comment]
commit ID : b7b76f3e932f023ee826ba5505e7ef3a3f74a208
