### ISSUE TITLE
Pravopisna greška u imenovanju polja

### ISSUE THREAD

**Issue by spahicharis** [SoftverInzenjeringETFSA/SI2014Tim6#55]
Komponenta:
DodavanjeKorisnika.java

commit ID:
636f2dafd5c52e27abe202408ca29682d43072cc

Opis problema:
Na formi "Dodavanje korisnika" nalazi se pravopisna greška.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju.
2. Selektovati korisnika/radnika iz tabele.
3. Kliknuti na dugme "Dodaj korisnika".
4. Nakon toga otvara se forma.

Dobijeni rezultat:
Polje za unos korisničkog imena se zove "Korisnicko ime".

Očekivani rezultat:
S obzirom da je na ostatku aplikacije primjenjen korektan pravopis očekivano je da i na ovoj formi bude u skladu sa tim.

**Comment by aidagranulo** [comment]
Ispravljeno.
commit ID: 21cb9b1528dd5d6ae0b2f31e1fb29c5e51ece926
