### ISSUE TITLE
Nije moguce izvrsiti login kao radnik

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#56]
Opis:

Problem nastaje kada se pokusa logirati na radnika. Ne funkcionise niti kada 
se doda novi korisnik sa usernameom i passwordom. Ugl ako se odabere neki od radnika i dodijeli mu se username i password, nakon odjave i pokusaja logiranja s istim password javlja neispravan format. 
![pokit_](https://cloud.githubusercontent.com/assets/11410413/7897686/cad9750a-06e4-11e5-8fa7-96d5fab1d89b.JPG)

**Comment by Strojki** [comment]
Commit ID: b7b76f3e932f023ee826ba5505e7ef3a3f74a208

**Comment by AlminHalilovic** [comment]
Kolega, duplicirao si samog sebe. Issue broj #54 je identičan ovome, a oba si ti postavio.
