### ISSUE TITLE
Nepostojeci test za klasu "Izvjestaj"

### ISSUE THREAD

**Issue by edos11** [SoftverInzenjeringETFSA/SI2014Tim6#57]
Komponenta:
Obrazac "Izvjestaj"

commit ID:
d23851c

Opis greške:
Ne postoji junit test za klasu Izvjestaj.java

**Comment by AlminHalilovic** [comment]
Ovo je duplicirani issue jer je kolegica Elma već spomenula taj nedostatak u issue #39.
