### ISSUE TITLE
Testovi svih klasa

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#60]
Opis: 

Mislim da su vam testovi jako sturo uradjeni. Nemate niti jedan test povezivanja i iscitavanja iz baze ili neke izmjene. Dosta set metoda nije testirano za svaku od klasa isto kao da su preskocene iz cudnog razloga. 

Comit ID:  636f2dafd5c52e27abe202408ca29682d43072cc

![pokit_tim6testovi](https://cloud.githubusercontent.com/assets/11410413/7899024/1d6e4028-0714-11e5-932c-d996bb288432.JPG)

**Comment by AlminHalilovic** [comment]
Kolega edos11 je napisao već nekoliko issua vezanih za nedostatak testova. Među tim prijavama se naročito ističu klase koje si ti dostavio kao dokaz na slici. Ovo je dakle dupliciran issue.
