### ISSUE TITLE
Rezervacija stolova za VIP

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#61]
Opis problema:

Kada se pokusa izvrsiti rezervacija stola koji je namjenjen VIP gostima to nije moguce jer u formi za dodavanje klijenata i postavljanje rezervacija nema opcije za VIP.

Commit ID:636f2dafd5c52e27abe202408ca29682d43072cc

![pokit_66e06d5277b3189ba8dc689f39089462](https://cloud.githubusercontent.com/assets/11410413/7899072/17298aa4-0716-11e5-9c0b-e1438ad0ad5e.jpg)

**Comment by tarikdemirovic** [comment]
Klijenta u VIP može promovisati samo šef, ne radnik. Tako da, taj sto se može rezervisati samo za klijenta koji je VIP - kojem je šef dao taj status.

**Comment by Strojki** [comment]
Da provjerio sam sa clanovima vaseg tima, ali iskreno mislim da to nema previse smisla iz razloga sto nije ostavljena nikakva opcija da u slucaju kada je restoran pun i dodju novi gosti a ovi vip stolovi su prazni onda oni stoje neiskoristeni. Ali to je samo jedan vid opaske nije potrebno ispravljati.

**Comment by AlminHalilovic** [comment]
Ima smisla kada se uzme u obzir da je osoba s kojom smo vodili intervju tražila da način rada aplikacije bude tačno takav.
