### ISSUE TITLE
Beskonacno otvaranje formi rezervacije stola

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#62]
Opis:

Kada se pokusa rezervisati sto za nekog klijenta i ako se klikne vise puta vise formi se otvori a ne ostane ova jedna koja bi trebala biti focus. 

Commit ID:636f2dafd5c52e27abe202408ca29682d43072cc

![pokit_8ce1a43fb75e779c6b794ba4d255cf6d](https://cloud.githubusercontent.com/assets/11410413/7899107/cf5f0374-0716-11e5-9b12-9a73ab9fbe18.jpg)

**Comment by aidagranulo** [comment]
Ispravka nad mogućnostima upravljanja formom Rezervacije dok su otvorene manje forme.
commit ID: 21cb9b1528dd5d6ae0b2f31e1fb29c5e51ece926
