### ISSUE TITLE
Rezervacije 3000te godine

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#63]
Opis:

Validno napraviti rezervaciju 3000te godine. Mislim da ovo nema puno smisla.
Commit ID:636f2dafd5c52e27abe202408ca29682d43072cc

![future](https://cloud.githubusercontent.com/assets/11410413/7899123/6ba4412c-0717-11e5-8fde-e7a99b3b6ae2.jpg)

**Comment by tarikdemirovic** [comment]
fuzzy je odrediti period do kojeg se može izvršiti rezervacija.
