### ISSUE TITLE
Problem kod kreiranja radnika sa istim imenom 

### ISSUE THREAD

**Issue by Strojki** [SoftverInzenjeringETFSA/SI2014Tim6#65]
Opis : 

Kada se kreiraju dva ista korisnika sa istim imenom i dodaju im se username i pass onda se desi sljedece prijavljuje da password nije dozvoljenog formata. 

Commit ID:636f2dafd5c52e27abe202408ca29682d43072cc

![bugkorisnik](https://cloud.githubusercontent.com/assets/11410413/7899397/9798486e-0721-11e5-938d-634f15267733.jpg)

**Comment by ElmirHodzic** [comment]
Resolved
